[Unit]
Description=Redis In-Memory Data Store                       
After=network.target                                         
Documentation=http://redis.io/documentation, man:redis-server(1)                                             

[Service]                                                    
Type=forking                                                 
User=redis                                                   
Group=redis                                                  
Environment=statedir=/website_efs/redis                              
PermissionsStartOnly=true                                    
PIDFile=/var/run/redis/redis-server.pid                                 
ExecStartPre=/bin/touch /var/log/redis6/redis6.log                   
ExecStartPre=/bin/chown redis:redis /var/log/redis6/redis6.log      
ExecStartPre=/bin/mkdir -p ${statedir}                       
ExecStartPre=/bin/chown -R redis:redis ${statedir}           
ExecStart=/website_efs/redis/redis-stable/src/redis-server /website_efs/redis/redis-stable/redis.conf --pidfile /var/run/redis/redis-server.pid  
ExecStop=/website_efs/redis/redis-stable/src/redis-cli shutdown                  
ExecReload=/bin/kill -USR2 $MAINPID                          
Restart=always                                               
RestartSec=3                                                 
                                                             
[Install]                                                    
WantedBy=multi-user.target